blank_issues_enabled: true
contact_links:
  - name: Baca Buku Pi Pi online
    url: https://pi.argakuka.com
    about: Telusuri daftar isi situs dan pencarian internal untuk menemukan bab yang sesuai terlebih dahulu.
